### ISSUE TITLE
Example building using core18 approach

### ISSUE THREAD

**Issue by abulka** [Jenyay/snap-examples#2]
Here is a version of the `snapcraft.yaml` example 0.5.1 which builds successfully under Ubuntu 18.04 using the core18 approach.  All I did was add the line `base: core18` and replace the `after: [desktop-gtk3]` with the `desktop-gtk3:` part. I also pointed to a more recent wxPython wheel.

```yaml
name: andy-testsnap-py
version: 0.5.1
summary: 'Single-line elevator pitch for your amazing snap'
description: "This is my-snap's description. You have a paragraph or two to tell the\nmost important story about your snap. Keep it under 100 words though,\nwe live in tweetspace and your description wants to look good in the snap\nstore.\n"
grade: devel
confinement: strict
base: core18
apps:
  andy-testsnap-py:
    command: 'desktop-launch python3 $SNAP/usr/bin/testsnap.py'
    plugs:
      - x11
      - unity7
      - pulseaudio
      - home
      - gsettings
      - network
    environment:
      LD_LIBRARY_PATH: '$LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio'
parts:
  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: 'https://github.com/ubuntu/snapcraft-desktop-helpers.git'
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
  andy-testsnap-py:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libssl-dev
      - libjpeg-dev
      - libtiff-dev
      - libsdl1.2-dev
      - libnotify-dev
      - freeglut3
      - ibus-gtk3
      - libwebkitgtk-3.0-0
      - zlib1g
      - libsm6
      - libpulse0
    python-packages:
      - 'https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.4-cp36-cp36m-linux_x86_64.whl'
    override-build: "snapcraftctl build\ncp $SNAPCRAFT_PART_SRC/testsnap.py $SNAPCRAFT_PART_INSTALL/usr/bin/\nchmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/testsnap.py\n"
```

Perhaps I can prepare a pull request for a v0.6 version once this is fully debugged :-) 

Because although it builds and even runs locally OK, I can't push it to the [snapcraft store](https://snapcraft.io/) because of a missing? reference to `libslang.so` which is symlinked.

```
Error while processing...
The store was unable to accept this snap.
  - package contains external symlinks: usr/lib/x86_64-linux-gnu/libslang.so
```

I have opened [an issue](https://forum.snapcraft.io/t/cant-push-because-of-symlinked-libslang-so/10274) on the snapcraft forums hoping someone can help.  Perhaps Eugeniy, you have a solution?
